import { ArrowUpRight, BrickWall, House, LockKeyhole, Ruler } from "lucide-react";
import { formatArea, type PublicRecords } from "../lib/records";

export function HomeView({ records }: { records: PublicRecords }) {
  const { groundFloor, firstFloor, porchMin, porchMax } = records.project.areasSqFt;
  const scale = Math.max(groundFloor, firstFloor, porchMax);
  const percentage = (area: number) => `${(area / scale) * 100}%`;
  return <>
    <header className="view-intro"><div className="eyebrow"><span className="eyebrow-mark" /> The place / Owner’s farmland</div><div className="view-intro-line"><div><h1>The home behind the record.</h1><p>A contemporary house built in Tamil Nadu with RCC concrete, steel reinforcement and red brick. The public view keeps the broad shape of the project without exposing its working plans.</p></div><span className="count-pill">Area estimates · owner-reported</span></div></header>
    <div className="home-layout"><section className="surface-card area-surface" aria-labelledby="area-heading"><div className="card-heading"><div><span className="overline">Scale of the build</span><h2 id="area-heading">Approximate areas</h2><p>These are the owner’s early measurements. The porch and overall total still need reconciliation.</p></div><Ruler size={21} strokeWidth={1.7} aria-hidden="true" /></div><div className="area-rows"><div className="area-row"><div><span>Ground floor</span><strong className="tabular-nums">≈ {formatArea(groundFloor)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--ground" style={{ width: percentage(groundFloor) }} /></div></div><div className="area-row"><div><span>First floor</span><strong className="tabular-nums">≈ {formatArea(firstFloor)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--first" style={{ width: percentage(firstFloor) }} /></div></div><div className="area-row"><div><span>Ground-floor RCC porch</span><strong className="tabular-nums">≈ {formatArea(porchMin)}–{formatArea(porchMax)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--porch" style={{ width: percentage(porchMin) }} />{porchMax > porchMin && <span className="area-range" style={{ left: percentage(porchMin), width: percentage(porchMax - porchMin) }} />}</div></div></div><div className="area-caption"><span>Bar lengths compare the areas shown; the darker porch segment shows its estimated range.</span><span>Not a floor plan</span></div></section>
      <aside className="home-aside"><section className="aside-panel material-panel"><span className="aside-panel-icon"><BrickWall size={18} strokeWidth={1.7} aria-hidden="true" /></span><h2>Built in the local way</h2><p>RCC concrete, steel rods and red bricks are part of the owner’s described construction. Brands, grades and quantities enter the ledger only when the records establish them.</p></section><section className="aside-panel"><span className="aside-panel-icon"><House size={18} strokeWidth={1.7} aria-hidden="true" /></span><h2>What comes next</h2><p>Dated photographs and a simplified exterior model can join this page after the owner chooses safe references for public viewing.</p></section></aside></div>
    <section className="privacy-surface" aria-labelledby="privacy-heading"><div><span className="privacy-icon"><LockKeyhole size={20} strokeWidth={1.7} aria-hidden="true" /></span><span className="overline">A deliberate boundary</span><h2 id="privacy-heading">The real plans stay private.</h2><p>Exact location, floor plans, wiring, worker identities and raw receipts are not part of the public site. Published entries use safe source descriptions, so readers can understand the record without seeing sensitive documents.</p></div><a className="button button--quiet" href="#journey">Read the journey <ArrowUpRight size={17} aria-hidden="true" /></a></section>
  </>;
}
