import { ArrowRight, LockKeyhole, Ruler } from "lucide-react";
import { formatArea, type PublicRecords } from "../lib/records";

export function HomeView({ records }: { records: PublicRecords }) {
  const { groundFloor, firstFloor, porchMin, porchMax } = records.project.areasSqFt;
  const scale = Math.max(groundFloor, firstFloor, porchMax);
  const percentage = (area: number) => `${(area / scale) * 100}%`;
  return <>
    <header className="view-intro"><div className="view-intro-line"><div><h1>Home profile</h1><p>A contemporary home in Tamil Nadu, built with RCC, steel and red brick. Approximate areas are published without exposing working plans.</p></div></div></header>
    <div className="home-layout"><section className="surface-card area-surface" aria-labelledby="area-heading"><div className="card-heading"><div><h2 id="area-heading">Approximate areas</h2><p>These are the owner’s early measurements. The porch range and overall total still need reconciliation.</p></div><Ruler size={21} strokeWidth={1.7} aria-hidden="true" /></div><div className="area-rows"><div className="area-row"><div><span>Ground floor</span><strong className="tabular-nums">≈ {formatArea(groundFloor)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--ground" style={{ width: percentage(groundFloor) }} /></div></div><div className="area-row"><div><span>First floor</span><strong className="tabular-nums">≈ {formatArea(firstFloor)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--first" style={{ width: percentage(firstFloor) }} /></div></div><div className="area-row"><div><span>Ground-floor RCC porch</span><strong className="tabular-nums">≈ {formatArea(porchMin)}–{formatArea(porchMax)} <small>sq ft</small></strong></div><div className="area-track" aria-hidden="true"><span className="area-fill area-fill--porch" style={{ width: percentage(porchMin) }} />{porchMax > porchMin && <span className="area-range" style={{ left: percentage(porchMin), width: percentage(porchMax - porchMin) }} />}</div></div></div><div className="area-caption"><span>Bar lengths compare the shown areas; the darker segment marks the porch estimate.</span><span>Not a floor plan</span></div></section>
      <aside className="home-aside"><section className="aside-panel material-panel"><h2>Construction record</h2><p>Reinforced concrete, steel rods and red brick are part of the owner’s description. Brands, grades and quantities enter the ledger only when sources establish them.</p></section><section className="aside-panel"><h2>Further documentation</h2><p>Dated photographs and a simplified exterior model may be added when references are selected for public viewing.</p></section></aside></div>
    <section className="privacy-surface" aria-labelledby="privacy-heading"><div><span className="privacy-icon"><LockKeyhole size={20} strokeWidth={1.7} aria-hidden="true" /></span><h2 id="privacy-heading">Working plans stay private.</h2><p>Exact location, floor plans, wiring, worker identities and raw receipts stay off the public site. Published entries use safe source descriptions, so readers can understand the record without seeing sensitive documents.</p></div><a className="button button--quiet" href="#journey">Read the journey <ArrowRight size={17} aria-hidden="true" /></a></section>
  </>;
}
